### ISSUE TITLE
`:lcd` breaks molder when starting vim with current directory

### ISSUE THREAD

**Issue by 4513ECHO** [mattn/vim-molder#17]
## Describe the bug

`:lcd` breaks molder when starting vim with current directory.
This bug was occurred in both of vim and neovim.

## Step to Reproduce

minimal vimrc:

```vim
if &compatible
  set nocompatible
endif
set rtp^=/path/to/github.com/mattn/vim-molder
```

* `vim -Nu molder.vimrc .` to start vim
* `:split`
* `:wincmd j`
* `:lcd ~`
* `:edit`

Then, the content of the another window is broken.
I think molder should expand `.`.

**Comment by mattn** [comment]
Could you please explain what is broken? I couldn't reproduce on Windows.

**Comment by mattn** [comment]
I could reproduce this on Linux.
