### ISSUE TITLE
Go to parent directory -- position cursor on directory name

### ISSUE THREAD

**Issue by habamax** [mattn/vim-molder#3]
Is is possible to position cursor on the directory you came from?

Like dirvish and vaffle do?

1. you are inside `~/.vim` dir and pressed `-`
2. in the parent directory cursor is on the first row but it would be nice if it was on a `.vim`.

**Comment by habamax** [comment]
It could be done with this:

```
function! molder#up() abort
  let l:dir = fnamemodify(b:dir, ':p:h:h:gs!\!/!')
  let l:pos_dir = fnamemodify(b:dir, ':p:h:t')
  exe 'edit' l:dir
  silent call search('^'.l:pos_dir.'/')
endfunction
```

**Comment by mattn** [comment]
Will look in later. I think molder should have to implement.
