### ISSUE TITLE
"r" doesn't reload directory

### ISSUE THREAD

**Issue by habamax** [mattn/vim-molder#4]
if I press `r` on molder buffer, vim goes to replace mode.

`:map r` shows nothing.

**Comment by mattn** [comment]
Dup in #2

**Comment by habamax** [comment]
I have tried new version:

1. `r` is still doesn't work (and documentation states it is now `<leader>r`
2. `<leader>r` goes to rename file (I guess it is from operations plugin?)

PS,

`<leader>-r` works... but it is really counter-intuitive :)

I would either not map it at all or map it to `R` or `r`.
