### ISSUE TITLE
position cursor on a file from which molder was run

### ISSUE THREAD

**Issue by habamax** [mattn/vim-molder#7]
Is it possible to position cursor on a file like dirvish and vaffle do?

1. edit `~/.vim/vimrc`
2. then run `:e.`
3. cursor is on top of molder buffer, would be nice if it was positioned on `vimrc` file.

**Comment by mattn** [comment]
Will implement this.

**Comment by habamax** [comment]
in dirvish it only works if mapping `-` is called.

**Comment by habamax** [comment]
Thx!

It works if a file you are editing in the same working directory, but doesn't work if a file was opened in subdirectory.

Is there a way I can call molder with a mapping providing current file directory as parameter?

![vim-molder](https://user-images.githubusercontent.com/234774/94936205-a0aae980-04d6-11eb-8a3b-22b1eb0d693a.gif)

**Comment by habamax** [comment]
Ha! I can `:noremap - :e :p:h<CR>`

**Comment by habamax** [comment]
Thank you very much!
